name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 3.7.71.233
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            # Install Node.js if not already installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            # Go to home directory
            cd ~
            # Create deploy script
            cat > deploy.sh << 'EOL'
            #!/bin/bash
            cd ~/class100xdevs-ci-cd-classweek25
            git pull origin main
            npm install
            NEXT_TELEMETRY_DISABLED=1 npm run build --no-lint
            npm run start
            EOL
            # Make deploy script executable
            chmod +x deploy.sh
            # Run deployment
            ./deploy.sh